nelmio_cors:
    defaults:
        origin_regex: false
        allow_credentials: false
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*']
        expose_headers: ['Link']
        max_age: 0
    paths:
        '^/api/': 
            allow_origin: ['^http://localhost:[0-9]+']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['*']
            max_age: 3600
        '^/api/edit': 
            allow_origin: ['^http://localhost:[0-9]+']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['*']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['X-Custom-Auth']
            max_age: 3600
            hosts: ['^api\.']
        '^/register':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['X-Custom-Auth']
            max_age: 3600
            hosts: ['^api\.']
