# config/routes.yaml
login:
    path: /api/login
    methods: ['POST']

    defaults:
      _format: json

getUser:
    path: /api/getUser
    controller: App\Controller\AuthController::user
    methods: ['GET']

edit:
    path: /api/edit/{id}
    controller: App\Controller\AuthController::edit
    methods: ['PUT']

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /view#/login
        permanent: true